- name: Installing Docker
  hosts: localhost
  become: yes

  tasks:
    - name: Installing PIP
      apt:
        name: ['python3-pip']
        state: latest

    # - name: Install ansible-playbook
    #   command: python3 -m pip install ansible-playbook

    - name: Install required system packages 
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'htop', 'net-tools', 'vim']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes

    - name: Installing docker
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose']
        state: latest

    - name: Starting docker service
      service:
        name: docker
        state: started

    - name: Enabling docker service
      service:
        name: docker
        enabled: yes

    - name: Adding ubuntu to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install required system packages
      apt: name=unzip state=latest update_cache=yes